-- MySQL Script generated by MySQL Workbench
-- Mon Nov 29 10:01:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
DROP SCHEMA IF EXISTS `ciaerea` ;
CREATE SCHEMA IF NOT EXISTS `ciaerea` DEFAULT CHARACTER SET utf8 ;
USE `ciaerea` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ciaerea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresas` ;

CREATE TABLE IF NOT EXISTS `empresas` (
  `idempresas` INT NOT NULL AUTO_INCREMENT,
  `CodEmp` VARCHAR(3) NOT NULL,
  `Nome` VARCHAR(50) NULL DEFAULT NULL,
  `site` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NULL,
  `anofundacao` INT NULL,
  PRIMARY KEY (`idempresas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tipos_avioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_avioes` ;

CREATE TABLE IF NOT EXISTS `tipos_avioes` (
  `idtipos_avioes` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipos_avioes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avioes` ;

CREATE TABLE IF NOT EXISTS `avioes` (
  `idavioes` INT NOT NULL AUTO_INCREMENT,
  `CodAviao` VARCHAR(8) NOT NULL,
  `Capacidade` INT NULL DEFAULT NULL,
  `valormercado` FLOAT NULL,
  `idempresas` INT NOT NULL,
  `idtipos_avioes` INT NOT NULL,
  PRIMARY KEY (`idavioes`, `idempresas`, `idtipos_avioes`),
  INDEX `fk_avioes_empresas1_idx` (`idempresas` ASC) VISIBLE,
  INDEX `fk_avioes_tipos_avioes1_idx` (`idtipos_avioes` ASC) VISIBLE,
  CONSTRAINT `fk_avioes_empresas1`
    FOREIGN KEY (`idempresas`)
    REFERENCES `empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avioes_tipos_avioes1`
    FOREIGN KEY (`idtipos_avioes`)
    REFERENCES `tipos_avioes` (`idtipos_avioes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aeroportos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aeroportos` ;

CREATE TABLE IF NOT EXISTS `aeroportos` (
  `idaeroportos` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(3) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idaeroportos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trechos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trechos` ;

CREATE TABLE IF NOT EXISTS `trechos` (
  `idtrechos` INT NOT NULL AUTO_INCREMENT,
  `Distancia` INT(11) NULL DEFAULT NULL,
  `idaeroportos_origem` INT NOT NULL,
  `idaeroportos_destino` INT NOT NULL,
  PRIMARY KEY (`idtrechos`, `idaeroportos_origem`, `idaeroportos_destino`),
  INDEX `fk_trecho_aeroportos1_idx` (`idaeroportos_origem` ASC) VISIBLE,
  INDEX `fk_trecho_aeroportos2_idx` (`idaeroportos_destino` ASC) VISIBLE,
  CONSTRAINT `fk_trecho_aeroportos1`
    FOREIGN KEY (`idaeroportos_origem`)
    REFERENCES `aeroportos` (`idaeroportos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trecho_aeroportos2`
    FOREIGN KEY (`idaeroportos_destino`)
    REFERENCES `aeroportos` (`idaeroportos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `voos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voos` ;

CREATE TABLE IF NOT EXISTS `voos` (
  `idvoos` INT NOT NULL AUTO_INCREMENT,
  `codvoo` VARCHAR(10) NULL,
  `idempresas` INT NOT NULL,
  PRIMARY KEY (`idvoos`, `idempresas`),
  INDEX `fk_voos_empresas1_idx` (`idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_voos_empresas1`
    FOREIGN KEY (`idempresas`)
    REFERENCES `empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rota` ;

CREATE TABLE IF NOT EXISTS `rota` (
  `idrotas` INT NOT NULL AUTO_INCREMENT,
  `hora_saida` TIME NULL DEFAULT NULL,
  `hora_chegada` TIME NULL DEFAULT NULL,
  `idtrechos` INT NOT NULL,
  `idvoos` INT NOT NULL,
  PRIMARY KEY (`idrotas`, `idtrechos`, `idvoos`),
  INDEX `fk_rota_trecho1_idx` (`idtrechos` ASC) VISIBLE,
  INDEX `fk_rota_voos1_idx` (`idvoos` ASC) VISIBLE,
  CONSTRAINT `fk_rota_trecho1`
    FOREIGN KEY (`idtrechos`)
    REFERENCES `trechos` (`idtrechos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rota_voos1`
    FOREIGN KEY (`idvoos`)
    REFERENCES `voos` (`idvoos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `viagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `viagens` ;

CREATE TABLE IF NOT EXISTS `viagens` (
  `idviagens` INT NOT NULL AUTO_INCREMENT,
  `dataviagem` DATE NOT NULL,
  `hora_saida_real` TIME NULL DEFAULT NULL,
  `hora_chegada_real` TIME NULL DEFAULT NULL,
  `idavioes` INT NOT NULL,
  `idrotas` INT NOT NULL,
  PRIMARY KEY (`idviagens`, `idavioes`, `idrotas`),
  INDEX `fk_viagem_avioes1_idx` (`idavioes` ASC) VISIBLE,
  INDEX `fk_viagem_rota1_idx` (`idrotas` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_avioes1`
    FOREIGN KEY (`idavioes`)
    REFERENCES `avioes` (`idavioes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_rota1`
    FOREIGN KEY (`idrotas`)
    REFERENCES `rota` (`idrotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
